### ISSUE TITLE
Might I ask the the license of this library?

### ISSUE THREAD

**Issue by TonyTangAndroid** [tiwiz/PasswordView#3]
Hi Tiwiz,

Might I ask the the license of this library?

Thanks,
Tony

**Comment by tiwiz** [comment]
Hello Tony,

You can use the library freely in any project, and it's provided as it is. The only thing that would make me very happy is that if you can link the repo inside the app in which you use the library (and maybe send me a couple of screenshots, so I can add it in the README).

**Comment by TonyTangAndroid** [comment]
Hi Tiwiz, 

Sure. I would be honoured to do this. I will send you screen shots once I publish my app, which should be expected by the end of this month.

Tony
